### ISSUE TITLE
Bug: potential correlation when running on HW + underused circuit

### ISSUE THREAD

**Issue by MattePalte** [alihakimtaskiran/QuantumDice#1]
# Environment

- **qiskit.__version__**: 0.45.2
- **Python version**: 3.10.12
- **Operating system**: Ubuntu 20.04

# What is happening?
In the Python file [QuantumDice.py](https://github.com/alihakimtaskiran/QuantumDice/blob/5515461e31f49a17f1f6d030854e0b53316badda/QuantumDice.py#L5) you instantiate a circuit of 3 qubits but you use only one to produce random values. Moreover, since you take all the measurement sequentially on the same qubit, they might not be independent in case of some hardware backends noise characteristics.

# How can we reproduce the issue?
Run the following code in the Python file:

```python
from qiskit import Aer, QuantumCircuit, execute
qd=QuantumCircuit(3,3)
for i in range(3):
    qd.h(0)
    qd.measure(0,i)

qd.draw()
```
Output:
```
     ┌───┐┌─┐┌───┐┌─┐┌───┐┌─┐
q_0: ┤ H ├┤M├┤ H ├┤M├┤ H ├┤M├
     └───┘└╥┘└───┘└╥┘└───┘└╥┘
q_1: ──────╫───────╫───────╫─
           ║       ║       ║
q_2: ──────╫───────╫───────╫─
           ║       ║       ║
c: 3/══════╩═══════╩═══════╩═
           0       1       2
```

# What should happen?
I would have expected to see all the three qubits used to produce random values. Also, I would have expected to see the measurements on different qubits to ensure independence.

# Any suggestions?
I would suggest:

```python
from qiskit import Aer, QuantumCircuit, execute
qd=QuantumCircuit(3,3)
for i in range(3):
    qd.h(i)
    qd.measure(i,i)
qd.draw()
```
Output:
```
     ┌───┐┌─┐
q_0: ┤ H ├┤M├──────
     ├───┤└╥┘┌─┐
q_1: ┤ H ├─╫─┤M├───
     ├───┤ ║ └╥┘┌─┐
q_2: ┤ H ├─╫──╫─┤M├
     └───┘ ║  ║ └╥┘
c: 3/══════╩══╩══╩═
           0  1  2
```

Resulting in something like:
```python
from qiskit import Aer, QuantumCircuit, execute
qd = QuantumCircuit(3, 3)
for i in range(3):
    qd.h(i)
    qd.measure(i, i)
print(qd.draw())

qc = Aer.get_backend("statevector_simulator")

def roll_dice():
    # get one shot
    result = execute(qd, qc, shots=1).result()
    counts = result.get_counts()
    # convert to integer
    val = int(list(counts.keys())[0], 2)
    print(f"Quantum-Dice rolled: {val}")
    if val not in (1, 2, 3, 4, 5, 6):
        val = roll_dice()
    return val

while True:
    input("Press enter to roll Quantum-Dice")
    print(roll_dice())
```

Thanks in advance, I wish you a happy and productive day.

**Comment by alihakimtaskiran** [comment]
Dear Matteo,
    Thank you for pointing a design flaw. While it seems a flaw, it actually works and generate "random" numbers. I attached result of 5000 independent measurement [here](https://github.com/alihakimtaskiran/QuantumDice/blob/main/QuantumDice.ipynb) . As for questioning, how did it work, it seems that as soon as qiskit perform the measurement, quantum state is simulated as mixed state and gates operate on density matrix <H^T| \rho | H> like this. Then in this case, probabilistic returns are exactly the same as pure state 1/sqrt2(|0>+|1>). So, it should work anyway. However, this doesn't mean the design is perfect. simulating mixed states requires more computational resources. Ultimately the best circuit is sequentially sampling from 
<pre>

     ┌───┤      ┌─┐
q_1: ┤ H ├────╫─┤M├
     └───┘      └╥┘
c: 1/═════════╩══╩═
           0
</pre>
. This method is pretty efficient, given range N, it needs logN steps to get random number.
    Thank you for co-visioning with me on the matter. Have a productive and happy day.
